<a href="https://colab.research.google.com/github/Inderdev07/Python-Tutorial/blob/main/INDER.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Qno1:- Write program to check whether given number is prime or not

n= int (input ("Enter the number "))
if n > 1:
  for i in range(2, int(n/2)+1): 
     if (n % i) == 0:
          print(n, "is not a prime number")
          break
     else:
        print(n, "is a prime number")
     break   
else:
    print(n, "is not a prime number")

Enter the number 5
5 is a prime number


In [ ]:
 #Qno2:- Write a program to construct the pattern, using a nested for loop.
 n= int(input("enter the number"))
 n[1]
for i in range(n):
    for j in range(i):
        print ('* ', end="")
    print('')

for i in range(0,-1):
    for j in range(i):
        print('* ', end="")
    print('')

enter the number3


TypeError: ignored

In [ ]:
def pattern(n):
    for i in range(n):
        for j in range(i+1):
            print("*", end="")
        print()

num_rows = int(input("Enter the number of rows: "))
pattern(num_rows)


In [ ]:
#Qno 3:- Write a program to find those numbers which are divisible by 7 and multiple of 5, between 1500 and 2700 (both included).
nl=[]
for x in range(1500, 2701):
    if (x%7==0) and (x%5==0):
        nl.append(str(x))
print (','.join(nl))





In [ ]:
#Qno4:-check wheather the given string is palindrome or not
def isPalindrome(s):
    return s == s[::-1]
  
#1
s= "inder"
ans = isPalindrome(s)
 
if ans:
    print("Yes")
else:
    print("No")
    #2
s= "peep"
ans = isPalindrome(s)
 
if ans:
    print("Yes")
else:
    print("No")
    #3
s= "redder"
ans = isPalindrome(s)
 
if ans:
    print("Yes")
else:
    print("No")
    #4
s= "nishit"
ans = isPalindrome(s)
 
if ans:
    print("Yes")
else:
    print("No")
    #5
s= "poop"
ans = isPalindrome(s)
 
if ans:
    print("Yes")
else:
    print("No")

In [ ]:
def isPalindrome(s):
    return s == s[::-1]
  
#1
s= "inder"
ans = isPalindrome(s)

In [ ]:
#Qno5: weight assigned to each characters e.g a-1,b-2,c-3....z-26
 str69=inder
 res=0
 for i in str69:
   print(ord(1)-96)
   res=res+ord(1-96)
   print(res)

In [ ]:
 
# donot use in operator
flag = 1
str1 = "Indians" 
str2 = 'x' 
for c in str1 : 
  if str2 == c : 
    print ("true") 
    break
  else : 
    print ("false")

In [ ]:
#Q1 write a program to find the occurance of substring in given string
str1 = "Indians" ; str2 = "dia";
print (str1, str2)
#2
str1= "India"
str2= "INDIA"
str1 < str2


In [ ]:
# Q2 write a program to find íthe occurance of substring in given string
import re
text = 'Python exercises, PHP exercises, C# exercises'
pattern = 'exercises'
for match in re.finditer(pattern, text):
    s = match.start()
    e = match.end()
    print('Found "%s" at %d:%d' % (text[s:e], s, e))

In [ ]:
# take 3
flag = 0
str1 = "Indians" 
str2 = 's' 
for c in range (len(str1)):
  if str2[0] == str1[c]:
    flag = 1
    # put loop till the end of str2
    for k in range (len ( str2 )):
      if str2 [k]  == str1 [c+k] :  pass #  print ('true')
      else  : flag=0 # print('false')
       
 
    # if str2[1] == str1[c+1] :
    #   if str2[2] == str1[c+2] :
    #     flag =1 
    #     break
 
if flag == 1 : 
  print ("true")
else : 
  print ("false")

In [ ]:
#indexing
sum=0

for item in range(0, len(mylst), 4 ):
    #sum = sum + mylst[item]
    print(mylst[item])


print("The sum of the list is",  sum)

In [ ]:
marks= [45,56,56,45,78,76,78,45]
sum = 0

for i in range(0, len(marks)):
  if(marks[i] == 45):
    sum += marks[i]

print("Sum:", sum)

In [ ]:
marks = [45, 56, 56, 45, 78, 76, 78, 450, 34, 55,12,4,66]

for i in range(0, len(marks)):
  if (marks[i]%2==0):
    even_lst.append(marks[i])
  else:
    odd_lst.append(marks[i])
print(odd_list) 
print(even_list)


In [ ]:
marks = [45, 56, 56, 45, 78, 76, 78, 45]
sum = 0

for i in range(0, len(marks)):
  if(marks[i] == 45):
    sum += marks[i]

print("Sum:", sum)

In [ ]:
#checking for membership
marks = [45, 56, 56, 45, 78, 76, 78, 45]
i==0
for i in range 

In [ ]:
#123 find vowel....
mystr="India is my cOUntry"
vowel=0

for char in range(0, len(mystr)):
    s=mystr[char].upper()
    if s == "A" or s =="E" or s=="I" or s=="O" or s=="U":
        vowel = vowel +1
        
print("vowels are ", vowel)

In [ ]:
mystr="India is my cOUntry"
vowel=0
vowels = "aeiouAEIOU"

for char in range(0, len(mystr)): 
    if mystr[char] in vowels:
        vowel = vowel +1
        
print("vowels are ", vowel)

In [ ]:
#odd & even find in a given list


marks=[45,56,56,45,78,76,78,450,34,55,12,4,66]
odd_list=[]
even_list=[]

for i in range(0,len(marks)):
  if(marks[i]%2==0):
    even_list.append(marks[i])
  else: 
    odd_list.append(marks[i])

print(odd_list) 
print(even_list)

In [ ]:
#find odd and even numbers
marks =[45,98,558,558,585,69,5588,58,25,554,148,36952,125,258,588,888]
odd_list=[]
even_list=[]

for i in range(0,len(marks)):
  if (marks[i]%2==0):
    even_list.append(marks[i])
  else: 
    odd_list.append(marks[i])

print(odd_list) 
print(even_list)

In [ ]:
#find odd and even numbers
marks = [2,4,6,8,14,7,69,69,69]
even_list=[]
for i in range (0,len(marks)):
  if (marks[i]%2==0):
    even_list.append(marks[i])
  else:
    odd_list.append(marks[i])

    print(odd_list)
    print(even_list)

In [ ]:
3
#  Write a program to input three nos and print the greatest
a = int(input('Enter first number  : '))
b = int(input('Enter second number : '))
c = int(input('Enter third number  : '))

largest = 0

if a > b and a > c :
    largest = a
elif b > c :
    largest = b
else :
    largest = c

print(largest, "is the largest of three numbers.")

In [ ]:
#tuples
tup=(4,'a', 5,'b',6,'c',7,'d',8,9)
tup[:2]+tup[8:10]


In [ ]:
#strings

mylist = "India is my country"
print(mylist[::-1])

In [ ]:
#reverse string
mylist = "India is my country"
revlist=[]
myWordList = mylist.split(" ")
print(myWordList)
for subList in myWordList:
    revlist.append(subList[::-1])
    

In [ ]:
mylist = "India is my country"
lst=""


In [ ]:
#assigments
student=["anu", 80,67,45, "seema",90,77,66, "Reeta", 76,45,99, "Ram",90,89,78]
# find the sum of marks of each student
# fIND THE AVERAGE MARKS OF EACH STUDENT
# Find teh aveerage of physics, chem and maths in the class
# Python Program to Calculate Total Marks Percentage and Grade of a Student

phy=0
chem=0
maths=0
for i in range(0,len(student), 4):
    phy= phy + student[i+1]
    chem= chem + student[i+2]
    maths= maths +student[i+3]
    
print("Average of physics is :", phy/4)
print("Average of chemistry is :", chem/4)
print("Average of maths is :", maths/4)
print(phy + chem + maths)/3

In [ ]:
# Write a program to input two numbers, add them, multiply them, divide them, find remainder.

num1 = int(input("Enter First Number: "))
num2 = int(input("Enter Second Number: "))

print("Enter which operation would you like to perform?")
ch = input("Enter any of these char for specific operation +,-,*,/: ")

result = 0
if ch == '+':
    result = num1 + num2
elif ch == '-':
    result = num1 - num2
elif ch == '*':
    result = num1 * num2
elif ch == '/':
    result = num1 / num2
else:
    print("Input character is not recognized!")

print(num1, ch , num2, ":", result)


In [ ]:
# Q1 write a program to find the occurance of substring in given string
flag = 0
str1 = "i m inder"
str2 = 'der' 
for c in range (len(str1)):  #outer loop 
  if str2[0] == str1[c]:
    flag = 1
    # put loop till the end of str2
    for k in range (len ( str2 )):   # inner loop 
      if str2 [k]  == str1 [c+k] :  pass #  print ('true')
      else  : flag=0 # print('false')
 
if flag == 1 : 
  print ("true")
else : 
  print ("false")

In [ ]:
#list practice

lst=[45,56,67,78,45,34,56,77,88,77,33,44,33,55,66,56]
lst.count(45)

In [ ]:
#empty list
uniquelist=[]
#pick only unique elements
lst=[45,45,77,78,45,34,56,77,88,77,33,44,33,77,66,56]

for number in lst:
    if number in uniquelist:
        pass
    else:
        uniquelist.append(number)
        print(uniquelist)

In [ ]:
set(lst)

In [ ]:
s1={4,5,6,7}
type s

In [ ]:
#Q from the given list count every fruit
fruits=["mango","orange","mango","banana","grape", "orange", "orange", "pear", "orange",
       "mango","orange","mango","banana","grape", "orange", "orange", "pear", "orange",
       "mango","orange","mango","banana","grape", "orange", "orange", "pear", "orange",
       "mango","orange","mango","banana","melon", "orange", "orange", "pear", "orange"]
fruits_unique=list(set(fruits))
for i in fruits_unique:
    print(i,fruits.count(i))

orange 16
banana 4
pear 4
melon 1
mango 8
grape 3


In [ ]:
#Q:- arrange the words in a given string as per decresing order of their weight


In [ ]:
# given list to find even number
lst1=[45,45,77,78,45,34,56,77,88,77,33,44,33,77,66,56]
count=0
for i in lst1:
    if(i%2 == 0):
      print(i)


In [ ]:
# given list to count even number 
lst1=[45,45,77,78,45,34,56,77,88,77,33,44,33,77,66,56]
count=0
for i in lst1:
    if(i%2 == 0):
      count=count+1
print(count)


In [ ]:
#display the count of even and odd number not equal to zero
lst1 = [233,0,114,55,23]
count=0
for i in lst1:
    if(i%2 == 0):
      count=count+1
      
print(count)

In [ ]:
#display the count of even and odd number not equal to zero
lst1=[1000,2,8,69,89,44,66,114,55,23,93,25,3,7]
counte=0
counto=0
for i in range(len(lst1)):
    if lst1[i] %2== 0:
            counte=counte+1
    else:
        counto=counto+1
        
print("no. of even elements: ",counte)
print("no. of odd elements: ",counto)

In [ ]:
# Q1 : Display the count of numbers divisible by 5  and count of numbers divisible by 3
# lst1 = [12,15,55,73,30,21,59]
# Q2 : display the count of character 's' in string 'sun is synonymous to strength'
#Q3. Given String India . Print the characters of the given string 
# no of time as per postional value
Inndddiiiiaaaaa
I(1)n(2)d(3)i(4)a(5)
#Q4. Given number 4783 . Print the numbers of the given integer number 
# no of time as per postional value
4778883333
4(1)7(2)8(3)3(4)


In [ ]:
# Q1 : Display the count of numbers divisible by 5  and count of numbers divisible by 3
# lst1 = [12,15,55,73,30,21,59]
lst1 = [12,15,55,73,30,21,59]
count_by_5 = 0
count_by_3 = 0
for number in lst1:
    if number % 5 == 0:
        count_by_5 += 1
    if number % 3 == 0:
        count_by_3 += 1

print("Count of numbers divisible by 5: ", count_by_5)
print("Count of numbers divisible by 3: ", count_by_3)


In [ ]:
# Q2 : display the count of character 's' in string 'sun is synonymous to strength'
def count(s, c) :
    res = 0
    for i in range(len(s)) :
        if (s[i] == c):
            res = res + 1
    return res
str= "sun is synonymous to strength"
c = 's'
print(count(str, c))

In [ ]:
#Q3. Given String India . Print the characters of the given string 
# no of time as per postional value
string = "India"
for char in string:
    print(char)


In [ ]:
#5 Print the greatest digit out of the given number
num=(input("Enter Number: "))
l=list(num)
max(l)

In [ ]:
#2 Print the reverse of the  given number
#1
number=4783
reverse_number = int((str(number))[::-1])
print(reverse_number)
#2
number=9876543210
reverse_number = int((str(number))[::-1])
print(reverse_number)

In [ ]:
#write a program to input three nos.& print the greatest
a = int(input('Enter first number  : '))
b = int(input('Enter second number : '))
c = int(input('Enter third number  : '))

largest = 0

if a > b and a > c :
    largest = a
elif b > c :
    largest = b
else :
    largest = c

print(largest, "is the largest of three numbers.")

In [ ]:
#Qno.3 print sum of first 10 number
n = int(input("Enter number"))
sum = 0
for num in range(1, n + 1, 1):
    sum = sum + num
print("Sum of first ", n, "numbers is: ", sum)

In [ ]:
#Qno.1:-
#enter a four digit number chech whether its leap year
year = int(input('Enter year : '))

if (year%4 == 0 and year%100 != 0) or (year%400 == 0) :
    print(year, "is a leap year.")
else :
    print(year, "is not a leap year.")


In [ ]:
#q enter a no. and print whether its a prime 
num =11
if num > 1:
    for i in range(2, int(num/2)+1):
        if (num % i) == 0:
            print(num, "is not a prime number")
            break
    else:
        print(num, "is a prime number")
else:
    print(num, "is not a prime number")

In [ ]:
#print fibonicci series upto given terms

In [ ]:
tup=("adv,gf,hh,hhh,66,88,44,66,89")
tup1=tup[0:2]+tup[6:9]

In [ ]:
sentence="the latest chatgtp has become a challange for google"
def remove_vowels(sentence):
    vowels = "aeiouAEIOU"
    return "".join([char for char in sentence if char not in vowels])

sentence = "the latest chatgtp has become a challenge for google"
print(remove_vowels(sentence))

In [ ]:
sentence="81% of Flipkart employees would recommend working there to a  \
friend based on Glassdoor reviews. Employees also rated Flipkart 3.6 \
out of 5 for work life balance, 4.1 for culture and values and 4.0 for career opportunities."
stopwords=["in", "of","and", "can", "on", "the", "for", "it", "a", "are", "he", "she", "us"]
impwords=["delicious", "relish", "enjoyed", "tasty", "lovely", "nice"]
def remove_stopwords(sentence):
  stopwords = stopwords=["in", "of","and", "can", "on", "the", "for", "it", "a", "are", "he", "she", "us"]
  return "".join([words for words in sentence if words not in stopwords])
  stopwords = stopwords=["in", "of","and", "can", "on", "the", "for", "it", "a", "are", "he", "she", "us"]
print(remove_stopwords(sentence))

In [ ]:
sentence="81% of Flipkart employees would recommend working there to a  \
friend based on Glassdoor reviews. Employees also rated Flipkart 3.6 \
out of 5 for work life balance, 4.1 for culture and values and 4.0 for career opportunities."
def count_impwords(sentence, impwords):
    return sum([1 for c in sentence if c == impwords])

sentence ="81% of Flipkart employees would recommend working there to a  \
friend based on Glassdoor reviews. Employees also rated Flipkart 3.6 \
out of 5 for work life balance, 4.1 for culture and values and 4.0 for career opportunities."
impwords=["delicious", "relish", "enjoyed", "tasty", "lovely", "nice"]
print("The character '{}' appears {} times in the sentence.".format(char, count_char(sentence, char)))


In [ ]:
maillist=["From stephen.marquard@gmail.com Sat Jan  5 09:14:16 2008",
          "From rahul@nielit.gov.in Sat Jan  5 10:24:16 2008",
          "From stephen.marquard@gmail.com Sat Jan  5 09:14:16 2015",
          "From anita@nielit.gov.in Sat Jan  5 11:14:16 2008",
          "From rajeshkumar@yahoo.com Sat Jan  5 09:14:16 2008",
          "From meenu@yahoo.com Sat Feb  5 10:14:16 2019",
          "From rashmi@rediff.com Sun Jan  5 09:14:16 2022", 
          "From rashmi@gmail.com Sun Feb  5 10:14:16 2012",
          "From rash@gmail.com Sun Jan  5 12:14:16 2021" , 
          "From rash@rediff.com Sun Jan  5 09:14:16 2020",
         "From stephen.marquard@gmail.com Sat Jan  5 09:14:16 2022",
          "From rahul@nielit.gov.in Sat Jan  5 10:24:16 2008",
          "From stephen.marquard@gmail.com Sat Jan  5 09:14:16 2023",
          "From anita@nielit.gov.in Sat Jan  5 09:14:16 2008",
          "From rajeshkumar@yahoo.com Sat Jan 2 10:14:16 2008",
          "From meenu@yahoo.com Sat Jan 5 10:14:16 2019",
          "From rashmi@rediff.com Sun Jan 5 09:14:16 2011", 
          "From rash@rediff.com Sun Jan  5 09:14:16 2080",
         "From stephen.marquard@gmail.com Sat Jan  5 09:14:16 2008",
          "From rahul@nielit.gov.in Sat Jan  5 10:24:16 2008",
          "From stephen.marquard@mygmail.com Sat Jan  5 09:14:16 2008",
          "From anita@nielit.gov.in Sat Jan  5 11:14:16 2008"]
          def count_emails_by_time("maillist, start_time, end_time"):
          for email in maillist:
              count = 0
              time = email.split()[5].split(":")
              hour = int(time[0])
              if start_time <= hour < end_time:
                count + = 1
                return count
                start_time = 9
                end_time = 10
                print("Number of emails sent between {}:00 AM and {}:00 AM: {}".format(start_time, end_time, count_emails_by_time(maillist, start_time, end_time)))

In [ ]:
maillist=["From stephen.marquard@gmail.com Sat Jan  5 09:14:16 2008",
          "From rahul@nielit.gov.in Sat Jan  5 10:24:16 2008",
          "From stephen.marquard@gmail.com Sat Jan  5 09:14:16 2015",
          "From anita@nielit.gov.in Sat Jan  5 11:14:16 2008",
          "From rajeshkumar@yahoo.com Sat Jan  5 09:14:16 2008",
          "From meenu@yahoo.com Sat Feb  5 10:14:16 2019",
          "From rashmi@rediff.com Sun Jan  5 09:14:16 2022", 
          "From rashmi@gmail.com Sun Feb  5 10:14:16 2012",
          "From rash@gmail.com Sun Jan  5 12:14:16 2021" , 
          "From rash@rediff.com Sun Jan  5 09:14:16 2020",
         "From stephen.marquard@gmail.com Sat Jan  5 09:14:16 2022",
          "From rahul@nielit.gov.in Sat Jan  5 10:24:16 2008",
          "From stephen.marquard@gmail.com Sat Jan  5 09:14:16 2023",
          "From anita@nielit.gov.in Sat Jan  5 09:14:16 2008",
          "From rajeshkumar@yahoo.com Sat Jan 2 10:14:16 2008",
          "From meenu@yahoo.com Sat Jan 5 10:14:16 2019",
          "From rashmi@rediff.com Sun Jan 5 09:14:16 2011", 
          "From rash@rediff.com Sun Jan  5 09:14:16 2080",
         "From stephen.marquard@gmail.com Sat Jan  5 09:14:16 2008",
          "From rahul@nielit.gov.in Sat Jan  5 10:24:16 2008",
          "From stephen.marquard@mygmail.com Sat Jan  5 09:14:16 2008",
          "From anita@nielit.gov.in Sat Jan  5 11:14:16 2008"]
mail_dic={}
for log in maillist:
  strt=log.find('@')
  end=log.find(' ',strt+1)
  mail= log[strt+1:end]
  if mail not in mail_dic:
        mail_dic[mail]=1
  else:
    mail_dic[mail]= mail_dic[mail] + 1
              
mail_dic

{'gmail.com': 7,
 'nielit.gov.in': 6,
 'yahoo.com': 4,
 'rediff.com': 4,
 'mygmail.com': 1}

In [ ]:
# # #PYTHON LISTS:-
# # # guild=["vijay","inder","nishit","pooja","vishal","vju"]
# # # print(guild[6])
# # # #print(guild)
# # numbers=[4,6,8,9,3,4,5,6,7,7]
# # # print(numbers)
# # # print(numbers[2])
# # print[numbers.reverse()]
numbers=[2,3,55,66]
# print(max(numbers))
numbers.append(5)
numbers.append(5)
numbers.insert(5,89)
print(numbers)

In [ ]:
# ASSIGMENT NO 2:
#Q15. Enter a number. Check whether its prime or not.
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True

num = int(input("Enter a number: "))

if is_prime(num):
    print(num, "is a prime number.")
else:
    print(num, "is not a prime number.")


In [ ]:
# ASSIGMENT NO 2:not.
#Q13. Write a program to check a character is vowel or 
def is_vowel(char):
    vowels = ['a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U']
    if char in vowels:
        return True
    else:
        return False

char = input("Enter a character: ")

if len(char) > 1:
    print("Invalid input. Please enter a single character.")
else:
    if is_vowel(char):
        print(f"{char} is a vowel.")
    else:
        print(f"{char} is not a vowel.")


In [ ]:
#Write a Python program to enter month name and show total number of days in that month.
def days_in_month(month):
    months_31 = ["january", "march", "may", "july", "august", "october", "december"]
    months_30 = ["april", "june", "september", "november"]
    if month == "february":
        return 28
    elif month in months_31:
        return 31
    elif month in months_30:
        return 30
    else:
        return None

month = input("Enter the name of a month: ")

days = days_in_month(month)

if days is None:
    print("Invalid month name.")
else:
    print(f"{month} has {days} days.")


In [ ]:
# Write a Python program to construct the following pattern, using a nested loop 
# number.
# 1
# 22
# 333
# 4444
# 55555
# 666666
# 7777777
# 88888888
# 999999999
for i in range(2, 11):
    for j in range(i):
        print(i, end='')
    print()

In [ ]:
# code 1 : calculate the weight of the given string 
def strWeight ( myStr):
  ''' 
  showWeight1 method accepts String and 
  returns the interger weight
  ''' 
  res = 0
  for i in myStr : 
    res = res + ord(i)-96
  return(res) 

In [ ]:
name = [ "Manjeet", "Nikhil", "Shambhavi", "Astha" ]
roll_no = [ 4, 1, 3, 2 ]
marks = [ 40, 50, 60, 70 ]
student = list(zip(name,roll_no,marks))
Student_list=[]

for record in student:
    temp=[]
    for value in record:
        temp.append(value)
    Student_list.append(temp)
    temp=[]

for record in Student_list:
    if record[2]<= 50:
        record[2] += 10
Student_list
list(zip(name,roll_no,marks))


In [ ]:
name = [ "Manjeet", "Nikhil", "Shambhavi", "Astha", "inder","rajiv" ,"Rohit"]
roll_no = [ 4,6,6,68,3,56,988,2222,144, 1, 3, 2 ]
marks = [ 40, 50, 60, 70 ]
list_names=[]

if len(name)==len(roll_no)==len(marks):
    student = list(zip(name,roll_no,marks))
list_names.append(name)
list_names.append(roll_no)
list_names.append(marks)

max=0
index=0
for i in range(len(list_names)):
    if len(list_names[i]) > max:
        max = len(list_names[i])
        index=i

list_names[index]

In [ ]:
name = [ "Manjeet", "Nikhil", "Shambhavi", "Astha", "inder","rajiv" ,"Rohit"]
roll_no = [ 4,6,6,68,3,56,988,2222,144, 1, 3, 2 ]
marks = [ 40, 50, 60, 70 ]
def myzip(name,roll,marks):
    student=[]
    list_students=[]
    for i in range(len(name)):
      student.append(name[i])
      student.append(roll_no[i])
      student.append(marks[i])
      print(student)
      student=tuple(student)
      print(student)
      list_students.append(student)
      print(list_students)
      student=[]
    return list_students

def main():
    name = [ "Manjeet", "Nikhil", "Shambhavi", "Astha" ]
    roll_no = [ 4, 1, 3, 2 ]
    marks = [ 40, 50, 60, 70 ]
    lst=

In [ ]:
#qno1:-
def print_multiplication_table():
  n= int(input("Enter a number to print themultiplication table:"))
  if n>18:
    print("Nnumber is large")
  print("Multiplication of", n ,"is :")
  for i in range (1, n+1):
      print(n, "*", i, "=", n*i)
print_multiplication_table()


In [ ]:
# code 3 : merge the code 1 and code 2
str2 = "india is my  and i am indian"
#calculate the weight of each word in given string - str2
# then calculate the max out of these 
sweight = [] # create blank list
newstr = str2.split()
for s in newstr:
  print(s , strWeight(s))
  sweight.append(strWeight(s))
print (sweight)

max = sweight[0]
for i in sweight : 
  if i > max  : 
    max = i 

print(max)

NameError: ignored

In [ ]:
str= "india"
count=0
for i in range (len(str)):
  print(str[i])
  count= count +1
  print(count)

In [ ]:
Str="hello MY name iS iNDER dEV"
lower=0
upper=0
for i in Str:
	if(i.islower()):
			lower+=1
	else:
			upper+=1
print("lowercase",lower)
print("uppercase",upper)


In [ ]:
str1 = "inDeR"
for c in str1 :
  print (c)
  if (ord(c)>=65 and (ord(c)>=90): print("uppercase")
  if (ord(c)>=97 and (ord(c)>=122): print("lowercase")

SyntaxError: ignored

In [ ]:
def no_of_words(str1):
  count=1
  for i in range(0,len(str1)):
    if (str1[i]==' ' and str1[i+1]!=' ') :
      count=count+1
  return count
  str1 = " we  r indians "
print(no_of_words(str1))

In [ ]:
# sort the list without using any built-in method / ascending order
lst1 = [20,15,14,12,7,1]
print ( lst1) 
for k in range (len(lst1)-1):
  for i in range (len(lst1)-1):
    print (lst1[i], end = " ")

In [ ]:
# Q6  Take two lists, say for example these two:
#   a = [23,24,25,26,27,28,29,30,31,32]
#   b = [24,26,28,29,32]
# and write a program that returns a list that contains only the elements that are common between the lists (without duplicates). Make sure your program works on two lists of different sizes.
a = [23,24,25,26,27,28,29,30,31,32]
b = [24,26,28,29,32]
c=[]
for i in range(len(a)):
    if a[i] in b:
        c.append(a[i])
c=set(c)
print(c)

{32, 24, 26, 28, 29}


In [ ]:
#Q7 Write a program (function!) that takes a list and returns a new list that contains all the elements of the first list minus all the duplicates.
a = [69,68,69,29,11,12,13,14,12,13,68,69]

doublewords = set()
uniquewords = []
for x in a:
    if x not in doublewords:
        uniquewords.append(x)
        dup_items.add(x)

print(dup_items)

In [ ]:
# count the number of words in a string
def countWords(strIn):
  wordCount = 0
  if len(strIn) != 0:  #making sure there are some words in the string
    isWord = True
    if strIn[0] == " ": # so  that we correct the first loop iteration beforehand
      wordCount = -1
  else:
    return 0
  for i in strIn:
    if i != " ":
      isWord = True
    else: 
      if isWord: # if we had a word earlier we can increment
        wordCount += 1
        isWord = False
  if strIn[-1] != " ": wordCount += 1 # for last element if it doesn't end with a space
  return wordCount
print(countWords("  a   hi"))

In [ ]:
# accept 10 numbers from user (one at a time) and make list of these given numbers
z=[]
print("Enter 10 numbers...")
for i in range(0,10):
  z.append(int(input("Enter: ")))
print("Here is the list...")
print(z)

In [ ]:
# accept 10 numbers from user (one at a time) and make sorted list of these given numbers . donot use sort or any built in method
my_list = [-15, -26, 15, 1, 23, -64, 23, 76]
new_list = []

while my_list:
    min = my_list[0]  
    for x in my_list: 
        if x < min:
            min = x
    new_list.append(min)
    my_list.remove(min)    

print(new_list)

In [ ]:
#accept 10 numbers from user (one at a time) and display the max, min and average after each number is accepted
n = int(input("Enter number"))
sum = 0
for n in range(1, n + 1, 1):
    sum = sum + n
print("Sum of first ", n, "numbers is: ", sum)
average = sum / n
print("Average of ", n, "numbers is: ", average)

Enter number3
Sum of first  3 numbers is:  6
Average of  3 numbers is:  2.0


In [ ]:
#accept 10 numbers from user (one at a time) and display the max, min and average after each number is accepted
num_list = int[]
count = 1

while count <= 10:
    num = int(input("Enter a number: "))
    num_list.append(num)
    max_num = max(num_list)
    min_num = min(num_list)
    avg_num = sum(num_list)/len(num_list)
    print("Max: ", max_num)
    print("Min: ", min_num)
    print("Average: ", avg_num)
    count += 1

Enter a number: 4


TypeError: ignored

In [ ]:
#find max and min
NumList = []
Number = int(input("Please enter element length in list "))
for i in range(1, Number + 1):
    value = int(input("Please enter the Value of %d Element : " %i))
    NumList.append(value)

print("The Smallest Element in this List is : ", min(NumList))
print("The Largest Element in this List is : ", max(NumList))

In [ ]:
#create a new dictionary, after adding 1 in all the values
d={'a':1, 'b':20,'c':3,'d':44}
newdic={}
for k,v in d.items():
    newdic[k]=v+1
newdic


#this output    newdic={'a':2, 'b':21, c':4,'d':45}

{'a': 2, 'b': 21, 'c': 4, 'd': 45}

In [ ]:
d={'a':1, 'b':20,'c':3,'d':44}
newdic={}
for k,v in d.items():
    newdic[k]=v+1
newdic


In [ ]:
d={'vowels':['a','e','i','o','u'],"consonants": "bcdfghjklmnpqrstvwxyz"}
d["vowels"]

str="India is a democratic country"
vowelsstr="aeiou"
vowelslst=['a','e','i','o','u']
vowel=0
for char in str:
    if char in d["vowels"]:
        vowel=vowel+1
vowel

10

In [ ]:
def find_phonenumber(phonebook, name):
    for n, p in phonebook.item():
        if n == name:
            return p
    return None

phonebook = {"John Doe": "555-555-5555","Albert Einstein": "212-555-5555"}
print ("John Doe's phone number is", find_phonenumber(phonebook.item , "John Doe"))

AttributeError: ignored

In [ ]:
lst1=['inder',]
    lst1=set(lst)
    lst1

IndentationError: ignored

In [ ]:
lst1=['good','are','good','new','good','new','class','new',
    'good','are','good','new','good','new','class','new',
    'good','are','good','laptop','good','new','class','new',
    'good','are','good','table','good','new','class','new']
new_dic={}
lst1=set(lst)
for i in lst1:
  count=lst.count(i)  
  new_dic[i]=count

print(new_dic)

{'table': 1, 'class': 4, 'are': 4, 'laptop': 1, 'good': 12, 'new': 10}


In [ ]:

mail_dic={}
for log in maillist:
  strt=log.find('@')
  end=log.find(' ',strt+1)
  mail= log[strt+1:end]
  if mail not in mail_dic:
        mail_dic[mail]=1
  else:
    mail_dic[mail]= mail_dic[mail] + 1
              
mail_dic

NameError: ignored

In [ ]:
#{1: ['foresolutions.net'], 2: ['nielit.gov.in'], 4: ['yahoo.com', 'rediff.com'], 6: 'gmail.com']}.

In [ ]:
def myInsertList():
  lst =[]
  while True : 
    n = int (input("Enter number ")) 
    if (n==-1): break 
    if lst == [ ]:  lst.append(n)
    flag=0
    tlst=[]
    for i in range(len(lst)):
      if (lst[i] < n )  :
        tlst.append(lst[i])  
      else :
        if (flag==0):
          tlst.append(n) # this statement to be executed only once
          tlst.append(lst[i]) 
          flag=1
        else : tlst.append(lst[i])
    if (flag==0): # number to be inserted in greater than all the numbers in list 
      tlst.append(n)
    lst = tlst
  print(lst )

In [ ]:
#write a function to enter a string and return a histogram

def hist(s):
    d={}
    for char in s:
        if char != " ":
            if char in d:
                d[char]=d[char]+1
            else:
                d[char]=1
    return d

def finddic(d,char):
    if char in d:
        return True
    else:
        return False

def revdic(d):
    rev={}
    #{'s': 3, 'u': 2, 'c': 2, 'e': 1, 'f': 1, 'l': 1}
    #{1: ['e', 'f', 'l'], 2 : ['u', 'c'], 3: ['s']}
    for k,v in d.items():
        if v not in rev:
            rev[v] = [k]
        else:
            rev[v].append(k)
    return rev

def main():
    s=input("enter a string")
    d=hist(s)
    #write a function to search for a char in dictionary
    search=input("enter the char to search")
    print(d)
    ans=finddic(d, search)
    if ans==True:
        print(search, " was found in ", d)
    else:
        print("not found")
    rev = revdic(d)
    print(rev)
    main()

In [ ]:
dic= {
    "inder": "cse",
    "vijay": "me",
    "naveed": "civil",
}
print(dic["vijay" ])

me


In [ ]:
dic={
    78:"inder",
     69: "vijay"
}
print(dic[69])

vijay


In [ ]:
l 

In [ ]:
dic = {'John':'A', 'Emily':'A+', 'Betty':'B', 'Mike':'C', 'Ashley':'A'}
print(dic.keys())
print(dic.values())
for keys in dic.keys():
  print("the value corresponding to the key keys} is {dic[keys]}")

dict_keys(['John', 'Emily', 'Betty', 'Mike', 'Ashley'])
dict_values(['A', 'A+', 'B', 'C', 'A'])
the value corresponding to the key keys} is {dic[keys]}
the value corresponding to the key keys} is {dic[keys]}
the value corresponding to the key keys} is {dic[keys]}
the value corresponding to the key keys} is {dic[keys]}
the value corresponding to the key keys} is {dic[keys]}


In [ ]:
C:\Users\ASUS\PycharmProjects\

NameError: ignored

In [ ]:
dic = {'John':'A', 'Emily':'A+', 'Betty':'B', 'Mike':'C', 'Ashley':'A'}
print(dic.items)

<built-in method items of dict object at 0x7f4a651d7880>


In [ ]:
dict = {'inder':'A', 'rich':'b', 'poor':'c', 'awara':'d', 'rider':'e','gamer':'f','hockey':'g'}
for values in dict.values():
  print(dict.values())
  break
  for values in dict.keys():
    print(dict.keys())
    continue

dict_values(['A', 'b', 'c', 'd', 'e', 'f', 'g'])


In [ ]:
tup=(12,5)
tup1=(13,3)
def multiply_fractions(tup, tup1):
  tup = (2, 3)
  tup1 = (3, 4)
product = multiply_fractions(tup,tup1)
print(product)

None


In [ ]:
lst=[(12,4), (3,4), (54,3), (33,2), (91,2)]
small=lst[0][0]/lst[0][1]
big =lst[0][0]/lst[0][1]
print(small)
i=lst[0]
for item in lst:
    d=item[0]/item[1]
    if d < small:
        small=d
        i=item
    if d > big:
        big=d
        j=item
print("The smallest fraction with value ",small, " is :" ,i)   
print("The biggest fraction with value ",big, " is :" ,j)

3.0
The smallest fraction with value  0.75  is : (3, 4)
The biggest fraction with value  45.5  is : (91, 2)


In [ ]:
#Ques Find the tuple which has the maximum sum of its elements
lst=[(12,4,3,4,6,7,8), (3,4,56,67,5,4), (54,3,4,5), (33,2,1,45,55), (91,200)]
lst 
d=[]
for item in lst:
  d.append(sum(item))

lst[d.index(max(d))]

TypeError: ignored

In [ ]:
def getworst_captain(teams):
    return teams[-1][1]

teams = [
           ["COACH_ONE", "CAPTAIN_TWO", "THREE", "FOUR", "FIVE", "SIX", "SEVEN", "EIGHT", "NINE"],
           ["COACH_ABC", "CAPTAIN_DEF", "GHI", "JKL", "MNO", "PQR", "STU", "VWX", "YZA"],
           ["COACH_RAM", "CAPTAIN_SEETA", "GEETA", "MANU", "ROHIT", "SHIVA", "GAURI", "MANAV", "ANKIT"],
           ["COACH_TEN", "CAPTAIN_TEWNTY", "THIRTY", "FOURTY", "FIFTY", "SIXTY", "SEVENTY"]
           ]

getworst_captain(teams)

'CAPTAIN_TEWNTY'

In [ ]:
a = [2, 4, 5, 6, 7, 7, 8, 10, 38, 23, 23, 8, 2]

def unique(x):
myset = set(x)
return myset

print(unique(a))

IndentationError: ignored

In [ ]:
import numpy as np
print(np)

<module 'numpy' from '/usr/local/lib/python3.8/dist-packages/numpy/__init__.py'>


In [ ]:
#You are given 5 cylindrical containers with different radius and heights ranging #between 5 and 25 cm #Find out a) the volume of water that each container can contain, b) the total volume of water that all containers can contain, c) which container can hold the highest volume and how much, d) which container can hold the least volume and how much, e) what is 
#the mean, median and standard deviation of the volumes #of water that can be contained in the containers?

In [ ]:
const arr = [5, 2, 9, 12, 8, 3, 7, 1, 6, 10];
let max = arr[0];
for (let i = 1; i < arr.length; i++) {
  if (arr[i] > max) {
    max = arr[i];
  }
}

console.log("The biggest number in the array is: " + max);


SyntaxError: ignored

In [ ]:
# Q1 Make an array of 10 elements and find the biggest number inthe array'
# Anita Budhiraja12:01
# Q2 Find the product of all numbers in the array
# Q3 Sort the array
# Q 4 Take a 2 d array of rows 3 and columns 4, populate it with values.
# See the information of 1st row only
# change the values in the last column for all the rows as 0
# pick the odd and the even nos from 2 d array and create two 1d arrays independent arrays odd and even


In [ ]:
# Q1 Make an array of 10 elements and find the biggest number inthe array'
list1 = [10, 20, 4, 45, 99]

# sorting the list
list1.sort()

# printing the last element
print("Largest element is:", list1[-1])


In [ ]:
# Import numpy as np and print the version number
import numpy as np
print(np.__version__)

1.22.4


In [ ]:
# Create a 1D array of numbers from 0 to 9
# #> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)
import numpy as np
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Create a 3×3 numpy array of all True’s
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
import numpy as np.

a=numpy.array([[3,4,5,6],[6,7,8,1],[8,7,6,12]])
#axis 0 refers to rows
#axis 1 refers to cols

for i in a:
    for j in i:
        if j %2==0:
            print(j)

SyntaxError: ignored

In [ ]:
class Ticket:
    counter=0 
    def __init__(self,passenger_name,source,destination):
        self.__passenger_name=passenger_name
        self.__source=source
        self.__destination=destination
        self.Counter=Ticket.counter
        Ticket.counter+=1
    def validate_source_destination(self):
        if (self.__source=="Delhi" and (self.__destination=="Pune" or self.__destination=="Mumbai" or self.__destination=="Chennai" or self.__destination=="Kolkata")):
            return True
        else:
            return False

    def generate_ticket(self ):
        if True:
            __ticket_id=self.__source[0]+self.__destination[0]+"0"+str(self.Counter)
            print( "Ticket id will be:",__ticket_id)
        else:
            return False
    def get_ticket_id(self):
        return self.ticket_id
    def get_passenger_name(self):
        return self.__passenger_name
    def get_source(self):
        if self.__source=="Delhi":
            return self.__source
        else:
            print("you have written invalid soure option")
            return None
    def get_destination(self):
        if self.__destination=="Pune":
            return self.__destination
        elif self.__destination=="Mumbai":
            return self.__destination
        elif self.__destination=="Chennai":
            return self.__destination
        elif self.__destination=="Kolkata":
            return self.__destination

        else:
            return None

In [ ]:
# Q. Import numpy as np and print the version number.
import numpy as np
print(np.__version__)

1.22.4


In [ ]:
#Q. Create a 1D array of numbers from 0 to 9
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Create a 3×3 numpy array of all True’s
np.full((3, 3), True, dtype=bool)
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
#Q. Extract all odd numbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [ ]:
# How to replace items that satisfy a
# condition with another value in numpy array?
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
square = np.array([
[16, 3,   2,  13], 
[5,  10, 11,   8],
[9,  6,   7,  12],
[4, 15,  14,   1]
 ]

In [ ]:
import numpy as np

n = 3  # the size of the magic square
magic_constant = n * (n**2 + 1) // 2  # the sum of each row, column, and diagonal

# create an n x n array of zeros
magic_square = np.zeros((n, n), dtype=int)

# place the numbers in the magic square
i, j = 0, n // 2  # start in the middle of the top row
for num in range(1, n**2 + 1):
    magic_square[i, j] = num  # place the number in the current position
    # move up and to the right
    new_i = (i - 1) % n
    new_j = (j + 1) % n
    # if the next position is already filled, move down instead
    if magic_square[new_i, new_j]:
        i = (i + 1) % n
    else:
        i, j = new_i, new_j

# check that each row, column, and diagonal adds up to the magic constant
assert np.all(magic_square.sum(axis=0) == magic_constant)
assert np.all(magic_square.sum(axis=1) == magic_constant)
assert np.trace(magic_square) == magic_constant
assert np.trace(np.fliplr(magic_square)) == magic_constant

# print the magic square
print(magic_square)

[[8 1 6]
 [3 5 7]
 [4 9 2]]


In [ ]:
wines = np.genfromtxt("winequality-white.csv", delimiter=";", skip_header=1)
type(wines)

In [ ]:
wines.sum(axis=0)

array([3.35747500e+04, 1.36282500e+03, 1.63687000e+03, 3.13051500e+04,
       2.24193000e+02, 1.72939000e+05, 6.77690500e+05, 4.86874609e+03,
       1.56161300e+04, 2.39927000e+03, 5.14988800e+04, 2.87900000e+04])

In [ ]:
wines[wines[:,11]==5]

array([[ 8.1 ,  0.27,  0.41, ...,  0.56, 12.  ,  5.  ],
       [ 8.6 ,  0.23,  0.4 , ...,  0.53,  9.7 ,  5.  ],
       [ 7.9 ,  0.18,  0.37, ...,  0.63, 10.8 ,  5.  ],
       ...,
       [ 6.8 ,  0.22,  0.36, ...,  0.54,  9.2 ,  5.  ],
       [ 6.5 ,  0.23,  0.38, ...,  0.54,  9.7 ,  5.  ],
       [ 6.6 ,  0.32,  0.36, ...,  0.46,  9.6 ,  5.  ]])

In [ ]:
wines.shape

(4898, 12)

In [ ]:
import pygame
import random

pygame.init()

# Set up the display
width, height = 640, 480
screen = pygame.display.set_mode((width, height))
pygame.display.set_caption("Shooting Game")

# Load images
player_img = pygame.image.load("player.png")
bullet_img = pygame.image.load("bullet.png")
enemy_img = pygame.image.load("enemy.png")

# Set up the player
player_width, player_height = player_img.get_size()
player_x, player_y = width // 2, height - player_height
player_speed = 5

# Set up the bullet
bullet_width, bullet_height = bullet_img.get_size()
bullet_speed = 10

# Set up the enemy
enemy_width, enemy_height = enemy_img.get_size()
enemy_x, enemy_y = random.randint(0, width - enemy_width), -enemy_height
enemy_speed = 5

# Set up the score
score = 0
font = pygame.font.Font(None, 36)

# Game loop
running = True
while running:
    # Handle events
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
        elif event.type == pygame.KEYDOWN:
            if event.key == pygame.K_ESCAPE:
                running = False
            elif event.key == pygame.K_SPACE:
                # Fire bullet
                bullet_x, bullet_y = player_x + player_width // 2 - bullet_width // 2, player_y - bullet_height
                bullet_rect = pygame.Rect(bullet_x, bullet_y, bullet_width, bullet_height)
                bullet_speed_y = -bullet_speed

    # Update player position
    keys = pygame.key.get_pressed()
    if keys[pygame.K_LEFT] and player_x > 0:
        player_x -= player_speed
    elif keys[pygame.K_RIGHT] and player_x < width - player_width:
        player_x += player_speed

    # Update bullet position
    if 'bullet_rect' in locals():
        bullet_rect.move_ip(0, bullet_speed_y)
        if bullet_rect.top < 0:
            del bullet_rect
        else:
            # Check for collision with enemy
            enemy_rect = pygame.Rect(enemy_x, enemy_y, enemy_width, enemy_height)
            if bullet_rect.colliderect(enemy_rect):
                del bullet_rect
                enemy_x, enemy_y = random.randint(0, width - enemy_width), -enemy_height
                score += 1
            else:
                screen.blit(bullet_img, bullet_rect)

    # Update enemy position
    enemy_y += enemy_speed
    if enemy_y > height:
        enemy_x, enemy_y = random.randint(0, width - enemy_width), -enemy_height
    else:
        screen.blit(enemy_img, (enemy_x, enemy_y))

    # Draw player and score
    screen.blit(player_img, (player_x, player_y))
    score_text = font.render("Score: " + str(score), True, (255, 255, 255))
    screen.blit(score_text, (10, 10))

    # Update display
    pygame.display.flip()

# Clean up
pygame.quit()

ModuleNotFoundError: ignored

In [ ]:
import numpy as np
from PIL import image
image_file = Image.open("img_tiger_grey.jpg") # open colour image
image_file
np.array(image_file)
image_file = image_file.convert('L')
image_file.save('img_tiger_grey.jpg')

ImportError: ignored

In [ ]:
import pandas as pd
sales = pd.read_csv("sales3.csv")
sales


Customer_Number     Customer_Name          2016          2017  \
0            10001  Quest Industries  $125,000.00   $162,500.00    
1            10002   kara Industries  $125,000.00   $162,500.00    
2            10003   Dabu Industries  $154,000.00   $642,500.00    
3            10004   Hero Industries  $165,000.00   $642,500.00    
4            10005            XML Co  $125,000.00   $542,900.00    
5            10006      Uber Limited  $154,000.00   $456,870.00    
6            10007      Zara Pvt Ltd  $125,000.00   $129,000.00    
7            10008           Samsung  $154,000.00   $444,320.00    
8            10009            Airtel  $169,000.00   $435,000.00    

  Percent_Growth Jan_Units  Month  Day  Year Active  
0         30.00%       500      1   10  2015      Y  
1         60.00%       500      1   10  2015      Y  
2         50.00%    closed      1   10  2015      N  
3         80.00%       600      1   11  2015      N  
4         60.00%       800      2   11  2015      Y  
5         50.00%       100      2   12  2015      Y  
6         16.00%       200      2   11  2015      Y  
7         40.00%       300      1   12  2015      Y  
8         60.00%       500      1   11  2015      Y

In [ ]:
import numpy as np
import cv2

def gaussian_blur(img, kernel_size):
    # Create a 2D Gaussian kernel with the given size
    kernel = np.zeros((kernel_size, kernel_size))
    center = kernel_size // 2
    sigma = 1.0
    for i in range(kernel_size):
        for j in range(kernel_size):
            x = i - center
            y = j - center
            kernel[i, j] = np.exp(-(x*2 + y2) / (2 * sigma*2))

    # Normalize the kernel to sum to 1
    kernel /= np.sum(kernel)

    # Apply the kernel to the image using convolution
    blurred = cv2.filter2D(img, -1, kernel)

    return blurred

In [ ]:
import numpy

arr = numpy.array([69,77,55,88,165,252,2552,252,225,14,2])

print(arr)

[  69   77   55   88  165  252 2552  252  225   14    2]


In [ ]:
import pandas as pd
sales = pd.read_csv("titanic3.csv")
sales

pclass  survived                                             name  \
0        1.0       1.0                    Allen, Miss. Elisabeth Walton   
1        1.0       1.0                   Allison, Master. Hudson Trevor   
2        1.0       0.0                     Allison, Miss. Helen Loraine   
3        1.0       0.0             Allison, Mr. Hudson Joshua Creighton   
4        1.0       0.0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1305     3.0       0.0                            Zabour, Miss. Thamine   
1306     3.0       0.0                        Zakarian, Mr. Mapriededer   
1307     3.0       0.0                              Zakarian, Mr. Ortin   
1308     3.0       0.0                               Zimmerman, Mr. Leo   
1309     NaN       NaN                                              NaN   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000    0.0    0.0   24160  211.3375       B5        S    2   
1       male   0.9167    1.0    2.0  113781  151.5500  C22 C26        S   11   
2     female   2.0000    1.0    2.0  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000    1.0    2.0  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000    1.0    2.0  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1305  female      NaN    1.0    0.0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000    0.0    0.0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000    0.0    0.0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000    0.0    0.0  315082    7.8750      NaN        S  NaN   
1309     NaN      NaN    NaN    NaN     NaN       NaN      NaN      NaN  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  
1309    NaN                              NaN  

[1310 rows x 14 columns]

In [ ]:
sales['cabin'].fillna("Not Available", inplace = True)
sales

pclass  survived                                             name  \
0        1.0       1.0                    Allen, Miss. Elisabeth Walton   
1        1.0       1.0                   Allison, Master. Hudson Trevor   
2        1.0       0.0                     Allison, Miss. Helen Loraine   
3        1.0       0.0             Allison, Mr. Hudson Joshua Creighton   
4        1.0       0.0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1305     3.0       0.0                            Zabour, Miss. Thamine   
1306     3.0       0.0                        Zakarian, Mr. Mapriededer   
1307     3.0       0.0                              Zakarian, Mr. Ortin   
1308     3.0       0.0                               Zimmerman, Mr. Leo   
1309     NaN       NaN                                              NaN   

         sex      age  sibsp  parch  ticket      fare          cabin embarked  \
0     female  29.0000    0.0    0.0   24160  211.3375             B5        S   
1       male   0.9167    1.0    2.0  113781  151.5500        C22 C26        S   
2     female   2.0000    1.0    2.0  113781  151.5500        C22 C26        S   
3       male  30.0000    1.0    2.0  113781  151.5500        C22 C26        S   
4     female  25.0000    1.0    2.0  113781  151.5500        C22 C26        S   
...      ...      ...    ...    ...     ...       ...            ...      ...   
1305  female      NaN    1.0    0.0    2665   14.4542  Not Available        C   
1306    male  26.5000    0.0    0.0    2656    7.2250  Not Available        C   
1307    male  27.0000    0.0    0.0    2670    7.2250  Not Available        C   
1308    male  29.0000    0.0    0.0  315082    7.8750  Not Available        S   
1309     NaN      NaN    NaN    NaN     NaN       NaN  Not Available      NaN   

     boat   body                        home.dest  
0       2    NaN                     St Louis, MO  
1      11    NaN  Montreal, PQ / Chesterville, ON  
2     NaN    NaN  Montreal, PQ / Chesterville, ON  
3     NaN  135.0  Montreal, PQ / Chesterville, ON  
4     NaN    NaN  Montreal, PQ / Chesterville, ON  
...   ...    ...                              ...  
1305  NaN    NaN                              NaN  
1306  NaN  304.0                              NaN  
1307  NaN    NaN                              NaN  
1308  NaN    NaN                              NaN  
1309  NaN    NaN                              NaN  

[1310 rows x 14 columns]

In [ ]:
import pandas as pd
crime = pd.read_csv("/content/District_wise_crimes_committed_IPC_2001_2012.csv")
crime

STATE       DISTRICT  YEAR  MURDER  ATTEMPT TO MURDER  \
0     ANDHRA PRADESH       ADILABAD  2001     101                 60   
1     ANDHRA PRADESH      ANANTAPUR  2001     151                125   
2     ANDHRA PRADESH       CHITTOOR  2001     101                 57   
3     ANDHRA PRADESH       CUDDAPAH  2001      80                 53   
4     ANDHRA PRADESH  EAST GODAVARI  2001      82                 67   
...              ...            ...   ...     ...                ...   
9012     LAKSHADWEEP    LAKSHADWEEP  2012       0                  0   
9013     LAKSHADWEEP          TOTAL  2012       0                  0   
9014      PUDUCHERRY       KARAIKAL  2012       5                  6   
9015      PUDUCHERRY     PUDUCHERRY  2012      24                 21   
9016      PUDUCHERRY          TOTAL  2012      29                 27   

      CULPABLE HOMICIDE NOT AMOUNTING TO MURDER  RAPE  CUSTODIAL RAPE  \
0                                            17    50               0   
1                                             1    23               0   
2                                             2    27               0   
3                                             1    20               0   
4                                             1    23               0   
...                                         ...   ...             ...   
9012                                          0     0               0   
9013                                          0     0               0   
9014                                          2     6               0   
9015                                         10     7               0   
9016                                         12    13               0   

      OTHER RAPE  KIDNAPPING & ABDUCTION  ...  ARSON  HURT/GREVIOUS HURT  \
0             50                      46  ...     30                1131   
1             23                      53  ...     69                1543   
2             27                      59  ...     38                2088   
3             20                      25  ...     23                 795   
4             23                      49  ...     41                1244   
...          ...                     ...  ...    ...                 ...   
9012           0                       0  ...      3                   3   
9013           0                       0  ...      3                   3   
9014           6                       2  ...      1                 186   
9015           7                      17  ...     20                 632   
9016          13                      19  ...     21                 818   

      DOWRY DEATHS  ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY  \
0               16                                                149     
1                7                                                118     
2               14                                                112     
3               17                                                126     
4               12                                                109     
...            ...                                                ...     
9012             0                                                  1     
9013             0                                                  1     
9014             0                                                  2     
9015             0                                                  7     
9016             0                                                  9     

      INSULT TO MODESTY OF WOMEN  CRUELTY BY HUSBAND OR HIS RELATIVES  \
0                             34                                  175   
1                             24                                  154   
2                             83                                  186   
3                             38                                   57   
4                             58                                  247   
...                  

In [ ]:
crime.MURDER

0       101
1       151
2       101
3        80
4        82
       ... 
9012      0
9013      0
9014      5
9015     24
9016     29
Name: MURDER, Length: 9017, dtype: int64

In [ ]:
crime.DISTRICT

0            ADILABAD
1           ANANTAPUR
2            CHITTOOR
3            CUDDAPAH
4       EAST GODAVARI
            ...      
9012      LAKSHADWEEP
9013            TOTAL
9014         KARAIKAL
9015       PUDUCHERRY
9016            TOTAL
Name: DISTRICT, Length: 9017, dtype: object

In [ ]:
state_year_data

NameError: ignored

In [ ]:
import pandas as pd
crime = pd.read_csv("/content/archive (1).zip")
crime

BadZipFile: ignored

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
loan_df = pd.read_csv('https://raw.githubusercontent.com/dsrscientist/DSData/master/loan_prediction.csv')
label_encoder = LabelEncoder()
loan_df['Gender'] = label_encoder.fit_transform(loan_df['Gender'])
loan_df['Married'] = label_encoder.fit_transform(loan_df['Married'])
loan_df['Education'] = label_encoder.fit_transform(loan_df['Education'])
loan_df['Self_Employed'] = label_encoder.fit_transform(loan_df['Self_Employed'])
loan_df['Property_Area'] = label_encoder.fit_transform(loan_df['Property_Area'])
loan_df['Loan_Status'] = label_encoder.fit_transform(loan_df['Loan_Status'])
X = loan_df.drop('Loan_Status', axis=1)
y = loan_df['Loan_Status']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
lr_model = LogisticRegression()
lr_model.fit(X_train, y_train)
y_pred = lr_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy: {:.2f}%'.format(accuracy*100))

ValueError: ignored